version: "3.7"
services:
    notebook-server:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - ./data:/app/data
            - ./notebooks:/app/notebooks
            - ./logs:/app/logs
            - ./requirements:/app/requirements
            - ./scripts:/app/scripts
        ports:
            # Jupyter port
            - "8888:8888"